name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    services:
      clickhouse:
        image: yandex/clickhouse-server:21.12
        options: >-
          --health-cmd "clickhouse-client -q 'select 1'" --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
          - 9000:9000

    steps:
      - name: Set up ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0-beta1
          stable: false

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: make test
